use std::fs;
use std::path::Path;

const EULA_TEXT: &str = "#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).\neula=true\n";

const SERVER_PROPERTIES: &str = r#"#Minecraft server properties
#Generated by MC Dashboard
enable-jmx-monitoring=false
online-mode=true
server-port=25565
server-ip=
motd=A Minecraft Server
max-players=20
gamemode=survival
difficulty=easy
view-distance=10
spawn-protection=16
max-world-size=29999984
level-name=world
generate-structures=true
allow-nether=true
enforce-whitelist=false
"#;

#[tauri::command]
pub fn accept_eula(server_dir: String) -> Result<String, String> {
    let dir = Path::new(&server_dir);
    if !dir.is_dir() {
        return Err(format!("Server directory does not exist: {server_dir}"));
    }
    let path = dir.join("eula.txt");
    if path.exists() {
        return Ok(format!("eula.txt already exists at {}", path.display()));
    }
    fs::write(&path, EULA_TEXT)
        .map_err(|e| format!("Failed to write eula.txt: {e}"))?;
    Ok(format!("eula.txt written to {}", path.display()))
}

#[tauri::command]
pub fn ensure_server_properties(server_dir: String) -> Result<String, String> {
    let dir = Path::new(&server_dir);
    if !dir.is_dir() {
        return Err(format!("Server directory does not exist: {server_dir}"));
    }
    let path = dir.join("server.properties");
    if path.exists() {
        return Ok(format!("server.properties already exists at {}", path.display()));
    }
    fs::write(&path, SERVER_PROPERTIES)
        .map_err(|e| format!("Failed to write server.properties: {e}"))?;
    Ok(format!("server.properties created at {}", path.display()))
}
